import {
  NewYork1, NewYork2, NewYork3, NewYork4, NewYork5, NewYork6, NewYork7, NewYork8, NewYork9,Mumbai1, Mumbai2, Mumbai3, Mumbai4, Mumbai5, Mumbai6, Mumbai7, Mumbai8, Mumbai9,London1, London2, London3, London4, London5, London6, London7, London8, London9,Paris1, Paris2, Paris3, Paris4, Paris5, Paris6, Paris7, Paris8, Paris9,
} from "./ImageLinks";

export const Hotels = {
  NewYork: [
    {
      id: 1,
      name: "Hyatt Grand Central",
      room: 3,
      bed: 4,
      price: 8000,
      Image: NewYork1,
      description: "Experience luxury with spacious rooms and a central location.",
    },
    {
      id: 2,
      name: "The Ritz-Carlton",
      room: 2,
      bed: 2,
      price: 6000,
      Image: NewYork2,
      description: "Elegance and sophistication in the heart of New York City.",
    },
    {
      id: 3,
      name: "Marriott Downtown",
      room: 4,
      bed: 5,
      price: 7500,
      Image: NewYork3,
      description: "Modern comfort with stunning city views.",
    },
    {
      id: 4,
      name: "Sheraton Times Square",
      room: 2,
      bed: 2,
      price: 5500,
      Image: NewYork4,
      description: "Conveniently located in Times Square.",
    },
    {
      id: 5,
      name: "The Peninsula",
      room: 5,
      bed: 6,
      price: 9500,
      Image: NewYork5,
      description: "Luxury by Central Park with world-class amenities.",
    },
    {
      id: 6,
      name: "Waldorf Astoria",
      room: 4,
      bed: 4,
      price: 8500,
      Image: NewYork6,
      description: "Timeless elegance in a historic landmark.",
    },
    {
      id: 7,
      name: "The Langham",
      room: 3,
      bed: 3,
      price: 7000,
      Image: NewYork7,
      description: "A blend of modern luxury and classic charm.",
    },
    {
      id: 8,
      name: "InterContinental Square",
      room: 3,
      bed: 4,
      price: 7800,
      Image: NewYork8,
      description: "Experience style and sophistication in Times Square.",
    },
    {
      id: 9,
      name: "Hilton Midtown",
      room: 2,
      bed: 3,
      price: 6700,
      Image: NewYork9,
      description: "Comfort and convenience in the heart of the city.",
    },
  ],

  // Mumbai hotels with descriptions
  Mumbai: [
    {
      id: 1,
      name: "Taj Mahal Palace",
      room: 5,
      bed: 6,
      price: 9999,
      Image: Mumbai1,
      description: "Unmatched luxury by the iconic Gateway of India.",
    },
    {
      id: 2,
      name: "Marriott Mumbai",
      room: 4,
      bed: 3,
      price: 7500,
      Image: Mumbai2,
      description: "Modern comforts with a touch of elegance.",
    },
    {
      id: 3,
      name: "Taj Lands End",
      room: 5,
      bed: 4,
      price: 8500,
      Image: Mumbai3,
      description: "Seaside retreat with breathtaking views.",
    },
    {
      id: 4,
      name: "JW Marriott Mumbai",
      room: 3,
      bed: 2,
      price: 7000,
      Image: Mumbai4,
      description: "Contemporary luxury in the heart of the city.",
    },
    {
      id: 5,
      name: "The Oberoi",
      room: 4,
      bed: 3,
      price: 9200,
      Image: Mumbai5,
      description: "Elegant rooms and impeccable service.",
    },
    {
      id: 6,
      name: "The St. Regis Mumbai",
      room: 5,
      bed: 4,
      price: 8700,
      Image: Mumbai6,
      description: "Luxury redefined with world-class amenities.",
    },
    {
      id: 7,
      name: "ITC Grand Central, Mumbai",
      room: 3,
      bed: 2,
      price: 6800,
      Image: Mumbai7,
      description: "A blend of luxury and Indian hospitality.",
    },
    {
      id: 8,
      name: "Trident, Bandra Kurla",
      room: 4,
      bed: 3,
      price: 7800,
      Image: Mumbai8,
      description: "Contemporary elegance in a bustling business district.",
    },
    {
      id: 9,
      name: "The Taj Mahal Tower",
      room: 5,
      bed: 4,
      price: 9400,
      Image: Mumbai9,
      description: "Historic luxury with views of the Arabian Sea.",
    },
  ],

  // London hotels with descriptions
  London: [
    {
      id: 1,
      name: "The Savoy",
      room: 4,
      bed: 4,
      price: 9000,
      Image: London1,
      description: "Iconic luxury on the banks of the Thames.",
    },
    {
      id: 2,
      name: "Park Plaza Westminster",
      room: 3,
      bed: 2,
      price: 7500,
      Image: London2,
      description: "Contemporary elegance in the heart of Westminster.",
    },
    {
      id: 3,
      name: "The Langham",
      room: 5,
      bed: 4,
      price: 8500,
      Image: London3,
      description: "Historic charm with modern amenities.",
    },
    {
      id: 4,
      name: "The Ritz London",
      room: 3,
      bed: 2,
      price: 9500,
      Image: London4,
      description: "Timeless luxury in the heart of London's West End.",
    },
    {
      id: 5,
      name: "Shangri-La Hotel",
      room: 5,
      bed: 4,
      price: 9800,
      Image: London5,
      description: "Luxury with stunning views from The Shard.",
    },
    {
      id: 6,
      name: "Corinthia Hotel London",
      room: 4,
      bed: 3,
      price: 8700,
      Image: London6,
      description: "Modern luxury in a restored Victorian building.",
    },
    {
      id: 7,
      name: "The Dorchester",
      room: 5,
      bed: 4,
      price: 10200,
      Image: London7,
      description: "Timeless elegance in the heart of Mayfair.",
    },
    {
      id: 8,
      name: "Ham Yard Hotel",
      room: 3,
      bed: 2,
      price: 7800,
      Image: London8,
      description: "Chic luxury in a vibrant Soho location.",
    },
    {
      id: 9,
      name: "Rosewood London",
      room: 4,
      bed: 3,
      price: 9200,
      Image: London9,
      description: "A historic hotel with modern sophistication.",
    },
  ],
  
  // Paris hotels with descriptions
  Paris: [
    {
      id: 1,
      name: "Four Seasons Hotel",
      room: 4,
      bed: 5,
      price: 6000,
      Image: Paris1,
      description: "Chic elegance in the heart of Paris.",
    },
    {
      id: 2,
      name: "Le Meurice",
      room: 3,
      bed: 3,
      price: 5000,
      Image: Paris2,
      description: "Classic luxury with stunning views of the Tuileries Garden.",
    },
    {
      id: 3,
      name: "Shangri-La Hotel Paris",
      room: 5,
      bed: 4,
      price: 7500,
      Image: Paris3,
      description: "Luxury with breathtaking views of the Eiffel Tower.",
    },
    {
      id: 4,
      name: "Le Bristol Paris",
      room: 4,
      bed: 3,
      price: 7000,
      Image: Paris4,
      description: "Elegance and charm in the heart of Faubourg Saint-Honoré.",
    },
    {
      id: 5,
      name: "Hôtel Plaza Athénée",
      room: 5,
      bed: 5,
      price: 8500,
      Image: Paris5,
      description: "Parisian luxury with views of the Eiffel Tower.",
    },
    {
      id: 6,
      name: "Le Royal Monceau",
      room: 4,
      bed: 4,
      price: 8000,
      Image: Paris6,
      description: "Artistic luxury in a stylish and modern setting.",
    },
    {
      id: 7,
      name: "The Westin Paris - Vendôme",
      room: 3,
      bed: 3,
      price: 6000,
      Image: Paris7,
      description: "Central location near the Louvre and Place Vendôme.",
    },
    {
      id: 8,
      name: "Hotel de Crillon",
      room: 4,
      bed: 4,
      price: 9000,
      Image: Paris8,
      description: "Historic luxury at a prestigious address on Place de la Concorde.",
    },
    {
      id: 9,
      name: "Mandarin Oriental, Paris",
      room: 3,
      bed: 3,
      price: 6500,
      Image: Paris9,
      description: "Contemporary elegance in the heart of Paris.",
    },
  ],
};
